export const chapterMap = {

    /* ================= CLASS 6 ================= */
  
    "class-6": {
  
      maths: [
        "Knowing Our Numbers",
        "Whole Numbers",
        "Playing With Numbers",
        "Basic Geometrical Ideas",
        "Understanding Elementary Shapes",
        "Integers",
        "Fractions",
        "Decimals",
        "Data Handling",
        "Mensuration",
        "Algebra",
        "Ratio and Proportion",
        "Symmetry",
        "Practical Geometry",
      ],
  
      science: [
        "Food: Where Does It Come From",
        "Components of Food",
        "Fibre to Fabric",
        "Sorting Materials",
        "Separation of Substances",
        "Changes Around Us",
        "Getting to Know Plants",
        "Body Movements",
        "Living Organisms",
        "Motion and Measurement",
        "Light Shadows",
        "Electricity and Circuits",
        "Fun With Magnets",
        "Water",
        "Air Around Us",
        "Garbage In Garbage Out",
      ],
    },
  
    /* ================= CLASS 7 ================= */
  
    "class-7": {
  
      maths: [
        "Integers",
        "Fractions and Decimals",
        "Data Handling",
        "Simple Equations",
        "Lines and Angles",
        "Triangle and Its Properties",
        "Congruence of Triangles",
        "Comparing Quantities",
        "Rational Numbers",
        "Practical Geometry",
        "Perimeter and Area",
        "Algebraic Expressions",
        "Exponents and Powers",
        "Symmetry",
        "Visualising Solid Shapes",
      ],
  
      science: [
        "Nutrition in Plants",
        "Nutrition in Animals",
        "Fibre to Fabric",
        "Heat",
        "Acids Bases and Salts",
        "Physical and Chemical Changes",
        "Weather Climate",
        "Winds Storms Cyclones",
        "Soil",
        "Respiration",
        "Transportation",
        "Reproduction in Plants",
        "Motion and Time",
        "Electric Current",
        "Light",
        "Water",
        "Forests",
        "Wastewater Story",
      ],
    },
  
    /* ================= CLASS 8 ================= */
  
    "class-8": {
  
      maths: [
        "Rational Numbers",
        "Linear Equations",
        "Understanding Quadrilaterals",
        "Practical Geometry",
        "Data Handling",
        "Squares and Square Roots",
        "Cubes and Cube Roots",
        "Comparing Quantities",
        "Algebraic Expressions",
        "Visualising Solid Shapes",
        "Mensuration",
        "Exponents and Powers",
        "Direct and Inverse Proportion",
        "Factorisation",
        "Graphs",
        "Playing With Numbers",
      ],
  
      science: [
        "Crop Production",
        "Microorganisms",
        "Synthetic Fibres",
        "Materials Metals and Non Metals",
        "Coal and Petroleum",
        "Combustion and Flame",
        "Conservation of Plants",
        "Cell Structure",
        "Reproduction in Animals",
        "Reaching Adolescence",
        "Force and Pressure",
        "Friction",
        "Sound",
        "Chemical Effects of Current",
        "Light",
        "Stars and Solar System",
        "Pollution",
      ],
    },
  
    /* ================= CLASS 9 ================= */
  
    "class-9": {
      maths: [
        "Number Systems",
        "Polynomials",
        "Coordinate Geometry",
        "Linear Equations in Two Variables",
        "Introduction to Euclid's Geometry",
        "Lines and Angles",
        "Triangles",
        "Quadrilaterals",
        "Circles",
        "Heron's Formula",
        "Surface Area and Volumes ",
        "Statistics",
       
      ],
      physics: [
        "Motion",
        "Force and Laws",
        "Gravitation",
        "Work and Energy",
        "Sound",
      ],
      chemistry: [
        "Matter Around Us",
        "Is Matter Pure",
        "Atoms and Molecules",
        "Structure of Atom",
      ],
      biology: [
        "Cell",
        "Tissues",
        "Diversity in Living",
        "Why Do We Fall Ill",
        "Natural Resources",
      ],
    },
  
    /* ================= CLASS 10 ================= */
  
    "class-10": {
      maths: [
        "Real Numbers",
        "Polynomials",
        "Pair of Linear Equations",
        "Quadratic Equations",
        "Arithmetic Progressions",
        "Triangles",
        "Coordinate Geometry",
        "Trigonometry",
        "Applications to Trigonometry",
        "Circles",
        "Area Related to Circles",
        "Surface Area and Volume",
        "Statistics",
        "Probability",
      ],
      physics: [
        "Light Reflection & Refraction",
        "Human Eye & Colourful World",
        "Electricity",
        "Magnetism",
      ],
      chemistry: [
        "Chemical Reactions",
        "Acids Bases Salts",
        "Metals and Non Metals",
        "Carbon Compounds",
      ],
      biology: [
        "Life Processes",
        "Control & Coordination",
        "Reproduction",
        "Heredity & Evolution",
        "Environment",
      ],
    },
  
    /* ================= CLASS 11 ================= */
  
    "class-11": {
      maths: [
        "Sets",
        "Relations and Functions",
        "Trigonometry",
        "Complex Numbers and Quadratic Equations",
        "Linear Inequalities",
        "Permutations and Combinations",
        "Binomial Theorem",
        "Sequences and Series",
        "Straight Lines",
        "Conic Sections",
        "Intro to 3-D Geometry",
        "Limits and Derivatives",
        "Statistics",
        "Probability"
      ],
      physics: [
        "Units & Measurements",
        "Motion in Straight Line",
        "Motion in  Planes",
        "Laws of Motion",
        "Work , Energy and  Power",
        "System of Particles and Rotational Motion",
        "Gravitation",
        "Mechanical Properties of Fluids",
        "Thermal Properties of Matter",
        "Thermodynamics",
        "Kinetic Theory",
        "Oscillations",
        "Waves",
      ],
      chemistry: [
        "Basic Concepts of Chemistry",
        "Structure of Atom",
        "Classification of Elements",
        "Chemical Bonding and Molecular Structure",
        "Thermodynamics",
        "Equilibrium",
        "Redox Reactions",
        "Organic Chemistry",
        "Hydrocarbons",
      ],
      biology: [
        "Living World",
        "Biological Classification",
        "Plant Kingdom",
        "Animal Kingdom",
        "Morphology of Flowering Plants",
        "Anatomy of Flowering Plants",
        "Structural Organisation in Animals",
        "Cell: The Unit of life",
        "Biomolecules",
        "Cell Cycle and Cell Division",
        "Photosynthesis in higher Plants",
        "Respiration in Plants",
        "Plant Growth and Development",
        "Breathing and Exchange of Gases",
        "Body Fluids and Circulation",
        "Excretory Products and thier Elimination",
        "Locomotion and Movement",
        "Neural control and coordination",
        "Chemical Coordination and Integration",
      ],
    },
  
    /* ================= CLASS 12 ================= */
  
    "class-12": {
      maths: [
        "Relations and Functions",
        "Inverse Trigonometry",
        "Matrices",
        "Determinants",
        "Continuity & Differentiability",
        "Application of Derivatives",
        "Integrals",
        "Application of Integrals",
        "Differential Equations",
        "Vector Algebra",
        "3-D Geometry",
        "Linear Programming",
        "Probability",
      ],
      physics: [
        "Electric Charges and Fields",
        "Electrostatics Potential and Capacitance",
        "Current Electricity",
        "Moving Charges and  Magnetism",
        "Magnetism and Matter",
        "Electromagnetic Induction",
        "Alternating Current",
        "Electromagnetic Waves",
        "Ray Optics and Optical Instruments",
        "Wave Optics",
        "Dual Nature of Radiation and Matter",
        "Atoms",
        "Nuclie",
        "Semiconductor"
      ],
      chemistry: [
        "Solid State",
        "Solutions",
        "Electrochemistry",
        "Chemical Kinetics",
        "The d and f -Blocks Element",
        "Coordination Compounds",
        "Haloalkanes and Haloarenes",
        "Alcohol , Phenols and Ethers",
        "Aldehydes ,Ketones and Carboxylic Acids",
        "Amines",
        "Biomolecules",
      ],
      biology: [
        "Sexual Reproduction in Flowering Plants",
        "Human Reproduction",
        "Reproductive Health",
        "Principles of Inheritance and Variation",
        "Molecular Basis of Inheritance ",
        "Evolution",
        "Human Health and Disease",
        "Microbes in Human Welfare",
        "Biotechnology: Principles and Processes",
        "Biotechnology and its Application",
        "Organism and Populations",
        "Ecosystem",
        "Biodiversity and Conservation",
      ],
    },
  
  };
  